# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='pull_number',
            field=models.IntegerField(verbose_name='pull request number'),
        ),
        migrations.AlterUniqueTogether(
            name='pull',
            unique_together=set([('pull_number', 'repository')]),
        ),
    ]
