# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20161025_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(db_index=True, max_length=64, verbose_name='git commit sha'),
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together=set([('sha', 'repository')]),
        ),
    ]
