# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-10-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20161025_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='pull',
            name='merged_by',
            field=models.CharField(default='null', max_length=32, verbose_name='merged by'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='changed_files',
            field=models.IntegerField(default=0, verbose_name='changed files'),
        ),
    ]
