# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='serving',
            field=models.BooleanField(default=True, verbose_name='on the job'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.Team', verbose_name='team'),
        ),
    ]
