# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20161024_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='leave date'),
        ),
    ]
